#+Title: Experiments 3d Printing
#+Author: Daniel Alexander Smith
#+Email: nalisarc@gmail.com

* 3d Printer
So my 3d printer is a [[https://www.amazon.com/gp/product/B07D218NX3/][Creality Ender 3]].
It's set up to use my raspberry pi and octopi to let me control it remotely
and a raspberry pi cam to moniter the prints and take neat timelapses.

As I do more experiments I will post the setup and results here.
* Openscad
** Installation
 [[https://www.openscad.org/documentation.html][OpenSCAD Documentation]]
While openscad has a nice app image file, I was having trouble with it finding input files that were relative to my working directory.
I followed this [[http://ubuntuhandbook.org/index.php/2019/01/install-openscad-ubuntu-18-10-18-04/][Guide on installing openscad]] and was able to fix my file issues.
Alternatively you can grab the appimage from [[https://www.openscad.org/downloads.html][the download page]]

** ob-scad
 The library ob-scad allows for the use of openscad blocks.
 These blocks allow for you to program objects to be rendered by the OpenSCAD program
 and can be later turned into 3d printed objects.
 Results of the scad blocks can be images, and at a later point I will experiment with gifs.
 [[https://github.com/wose/ob-scad][ob-scad Repo]]
** Things to Read
[[https://hackaday.io/page/5252-generating-nice-threads-in-openscad][Generating Nice Threads In OpenSCAD]]
[[https://www.openscad.org/cheatsheet/index.html][Cheatsheet]]
* Ideas
** TODO x axis limiter switch
So I apparently knocked the little metal switch off of my x axis limiter. The button still works but it rams the extruder into the mounting bracket when homing sometimes.
I think I'll see about printing out a new switch for the button.
This would be a little plastic clip that attaches to the side of the button, and has a thin layer of plastic extending diagonally.
So when the plasic is hit it stops the extruder.

I'll need to take measuments to be sure of the size.
** TODO Parafin Stretcher
I have a pretty neat electrofluidics chip that I want to use more often.
Unfortunately it requires making a very thin membrain and the only thing I have that works is parafin.
I need something to strech it out to the thin membrane reliably.

My plan for this is two rollers attached to gears and a crank.
When the crank turns it rotates the rollers in opposite directions by a predicatble amount.
** TODO Weekly Day/Night Pill Case
I found a really cool [[https://www.thingiverse.com/thing:2954076][Pill Case]] I've printed out two so far and they have been great.
The only thing I would change is to essentually merge them into 

#+name: pillcase-base
#+BEGIN_SRC scad
#+END_SRC

#+name: pillcase-mid
#+BEGIN_SRC scad
#+END_SRC

#+name: pillcase-lid
#+BEGIN_SRC scad
#+END_SRC

#+name: pillcase-skrew
#+BEGIN_SRC scad
#+END_SRC
** TODO Journal
It would be cool to make a journal with 3d parts and a leather cover
idek
** TODO Change bed to 3 point
Apparently a 3 point bed is easier to set than a 4 pint bed because /geometry/

[[3193722][Simple Ender 3 mod for 3-point tramming]]
[[thing:3400187][Locking ThumbWheels and 3-Point Hot Bed Leveling]]
[[thing:3415460][Hot Bed Leveling and 3-Point Mounting]]

* Thingiverse
#+LINK: thing https://www.thingiverse.com/thing:%s
[[thing:3574369][Ender 3 Troubleshoot Guide]]

[[https://reprap.org/wiki/RepRap][reprap wiki]]
