#+Title: Experiments 3d Printing
#+Author: Daniel Alexander Smith
#+Email: nalisarc@gmail.com

* 3d Printer
So my 3d printer is a [[https://www.amazon.com/gp/product/B07D218NX3/][Creality Ender 3]].
It's set up to use my raspberry pi and octopi to let me control it remotely
and a raspberry pi cam to moniter the prints and take neat timelapses.

As I do more experiments I will post the setup and results here.
* Openscad
[[https://www.openscad.org/documentation.html][OpenSCAD Documentation]]
** ob-scad
 The library ob-scad allows for the use of openscad blocks.
 These blocks allow for you to program objects to be rendered by the OpenSCAD program
 and can be later turned into 3d printed objects.
 Results of the scad blocks can be images, and at a later point I will experiment with gifs.
 [[https://github.com/wose/ob-scad][ob-scad Repo]]
** Objects

 #+name: cube
 #+BEGIN_SRC scad :file cube.png :tangle cube.scad 
 cube(5,5,5);
 #+END_SRC

 #+name: sphere
 #+BEGIN_SRC scad :file sphere.png
 sphere(5);
 #+END_SRC

 #+name: union
 #+BEGIN_SRC scad :file union.png
 #+END_SRC
* Ideas
** TODO x axis limiter switch
So I apparently knocked the little metal switch off of my x axis limiter. The button still works but it rams the extruder into the mounting bracket when homing sometimes.
I think I'll see about printing out a new switch for the button.
This would be a little plastic clip that attaches to the side of the button, and has a thin layer of plastic extending diagonally.
So when the plasic is hit it stops the extruder.

I'll need to take measuments to be sure of the size.
** TODO Parafin Stretcher
I have a pretty neat electrofluidics chip that I want to use more often.
Unfortunately it requires making a very thin membrain and the only thing I have that works is parafin.
I need something to strech it out to the thin membrane reliably.

My plan for this is two rollers attached to gears and a crank.
When the crank turns it rotates the rollers in opposite directions by a predicatble amount.
